# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rootie/risc16/risc16.srcs/sources_1/bd/risc16System/ip/risc16System_clk_wiz_0_0/risc16System_clk_wiz_0_0.xci
# IP: The module: 'risc16System_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rootie/risc16/risc16.srcs/sources_1/bd/risc16System/ip/risc16System_clk_wiz_0_0/risc16System_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc16System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rootie/risc16/risc16.srcs/sources_1/bd/risc16System/ip/risc16System_clk_wiz_0_0/risc16System_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc16System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rootie/risc16/risc16.srcs/sources_1/bd/risc16System/ip/risc16System_clk_wiz_0_0/risc16System_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc16System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rootie/risc16/risc16.srcs/sources_1/bd/risc16System/ip/risc16System_clk_wiz_0_0/risc16System_clk_wiz_0_0.xci
# IP: The module: 'risc16System_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rootie/risc16/risc16.srcs/sources_1/bd/risc16System/ip/risc16System_clk_wiz_0_0/risc16System_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc16System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rootie/risc16/risc16.srcs/sources_1/bd/risc16System/ip/risc16System_clk_wiz_0_0/risc16System_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc16System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rootie/risc16/risc16.srcs/sources_1/bd/risc16System/ip/risc16System_clk_wiz_0_0/risc16System_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'risc16System_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
