# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/rootie/Documents/digilent-xdc-master/Nexys-A7-100T-Master.xdc

# Block Designs: bd/risc16System/risc16System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System || ORIG_REF_NAME==risc16System} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_nexys_7seg_0_0/risc16System_nexys_7seg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_nexys_7seg_0_0 || ORIG_REF_NAME==risc16System_nexys_7seg_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_clk_wiz_0_0/risc16System_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_clk_wiz_0_0 || ORIG_REF_NAME==risc16System_clk_wiz_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_clk_div_0_0/risc16System_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_clk_div_0_0 || ORIG_REF_NAME==risc16System_clk_div_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_risc16_0_0/risc16System_risc16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_risc16_0_0 || ORIG_REF_NAME==risc16System_risc16_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_display_ctrl_0_0/risc16System_display_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_display_ctrl_0_0 || ORIG_REF_NAME==risc16System_display_ctrl_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_spi_slave_0_0/risc16System_spi_slave_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_spi_slave_0_0 || ORIG_REF_NAME==risc16System_spi_slave_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_CPU_Programmer_0_0/risc16System_CPU_Programmer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_CPU_Programmer_0_0 || ORIG_REF_NAME==risc16System_CPU_Programmer_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_mux_0_0/risc16System_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_mux_0_0 || ORIG_REF_NAME==risc16System_mux_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_clk_div_1_0/risc16System_clk_div_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_clk_div_1_0 || ORIG_REF_NAME==risc16System_clk_div_1_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_clock_bus_0_0/risc16System_clock_bus_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_clock_bus_0_0 || ORIG_REF_NAME==risc16System_clock_bus_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_vga_0_0/risc16System_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_vga_0_0 || ORIG_REF_NAME==risc16System_vga_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_clk_wiz_0_1/risc16System_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_clk_wiz_0_1 || ORIG_REF_NAME==risc16System_clk_wiz_0_1} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_ram_0_0/risc16System_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_ram_0_0 || ORIG_REF_NAME==risc16System_ram_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_MCU_0_0/risc16System_MCU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_MCU_0_0 || ORIG_REF_NAME==risc16System_MCU_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_or_gate_0_0/risc16System_or_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_or_gate_0_0 || ORIG_REF_NAME==risc16System_or_gate_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_Ctrl_Registers_0_0/risc16System_Ctrl_Registers_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_Ctrl_Registers_0_0 || ORIG_REF_NAME==risc16System_Ctrl_Registers_0_0} -quiet] -quiet

# IP: bd/risc16System/ip/risc16System_Video_Buffer_0_0/risc16System_Video_Buffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc16System_Video_Buffer_0_0 || ORIG_REF_NAME==risc16System_Video_Buffer_0_0} -quiet] -quiet

# XDC: bd/risc16System/risc16System_ooc.xdc
